/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ister.vista.formularios.internos;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Paola
 */
public class FrmiDateUtil extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmDateUtil
     */
    public FrmiDateUtil() {
        initComponents();
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtGrupo1 = new javax.swing.ButtonGroup();
        lblDateUtil = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbtTeoria = new javax.swing.JRadioButton();
        rbtEjemplos = new javax.swing.JRadioButton();
        rbtPractica = new javax.swing.JRadioButton();
        escritorioDateUtil = new javax.swing.JDesktopPane();

        lblDateUtil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDateUtil.setText("Date.Util");

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        rbtGrupo1.add(rbtTeoria);
        rbtTeoria.setText("Teoría");
        rbtTeoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtTeoriaActionPerformed(evt);
            }
        });

        rbtGrupo1.add(rbtEjemplos);
        rbtEjemplos.setText("Ejemplos");
        rbtEjemplos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEjemplosActionPerformed(evt);
            }
        });

        rbtGrupo1.add(rbtPractica);
        rbtPractica.setText("Práctica");
        rbtPractica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPracticaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtEjemplos)
                    .addComponent(rbtTeoria)
                    .addComponent(rbtPractica))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(rbtTeoria)
                .addGap(18, 18, 18)
                .addComponent(rbtEjemplos)
                .addGap(18, 18, 18)
                .addComponent(rbtPractica)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        escritorioDateUtil.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout escritorioDateUtilLayout = new javax.swing.GroupLayout(escritorioDateUtil);
        escritorioDateUtil.setLayout(escritorioDateUtilLayout);
        escritorioDateUtilLayout.setHorizontalGroup(
            escritorioDateUtilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );
        escritorioDateUtilLayout.setVerticalGroup(
            escritorioDateUtilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(escritorioDateUtil)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(lblDateUtil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDateUtil)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 180, Short.MAX_VALUE))
                    .addComponent(escritorioDateUtil))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtTeoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtTeoriaActionPerformed
        // TODO add your handling code here:
        escritorioDateUtil.removeAll();
        escritorioDateUtil.repaint();
        
        FrmiTeoriaDateUtil frmiteoria = new FrmiTeoriaDateUtil();
        escritorioDateUtil.add(frmiteoria);
        frmiteoria.setVisible(true);
        
        try {
            frmiteoria.setMaximum(true);
            frmiteoria.setMaximizable(true);
            frmiteoria.setSelected(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_rbtTeoriaActionPerformed

    private void rbtEjemplosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEjemplosActionPerformed
        // TODO add your handling code here:
        escritorioDateUtil.removeAll();
        escritorioDateUtil.repaint();

        FrmiEjemplosDateUtil frmiejemplos = new FrmiEjemplosDateUtil();
        escritorioDateUtil.add(frmiejemplos);
        frmiejemplos.setVisible(true);

        try {
            frmiejemplos.setMaximum(true);
            frmiejemplos.setMaximizable(true);
            frmiejemplos.setSelected(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_rbtEjemplosActionPerformed

    private void rbtPracticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPracticaActionPerformed
        // TODO add your handling code here:
        escritorioDateUtil.removeAll();
        escritorioDateUtil.repaint();
        
        FrmiPracticaDateUtil frmiPractica = new FrmiPracticaDateUtil();
        escritorioDateUtil.add(frmiPractica);
        frmiPractica.setVisible(true);
        
        try {
            frmiPractica.setMaximum(true);
            frmiPractica.setMaximizable(true);
            frmiPractica.setSelected(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_rbtPracticaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorioDateUtil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDateUtil;
    private javax.swing.JRadioButton rbtEjemplos;
    private javax.swing.ButtonGroup rbtGrupo1;
    private javax.swing.JRadioButton rbtPractica;
    private javax.swing.JRadioButton rbtTeoria;
    // End of variables declaration//GEN-END:variables
}
