/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ister.vista.formularios.internos;

import com.toedter.calendar.JCalendar;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Paola
 */
public class FrmiEjemplosCalendar extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmiEjemplosCalendar
     */
    public FrmiEjemplosCalendar() {
        initComponents();
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEjemplos = new javax.swing.JLabel();
        btnCalendarSinFormato = new javax.swing.JButton();
        btnCalendarConFormato = new javax.swing.JButton();

        lblEjemplos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEjemplos.setText("Ejemplos");

        btnCalendarSinFormato.setText("Calendar sin formato");
        btnCalendarSinFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarSinFormatoActionPerformed(evt);
            }
        });

        btnCalendarConFormato.setText("Calendar con formato");
        btnCalendarConFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarConFormatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(lblEjemplos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCalendarConFormato)
                            .addComponent(btnCalendarSinFormato))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEjemplos)
                .addGap(53, 53, 53)
                .addComponent(btnCalendarSinFormato)
                .addGap(35, 35, 35)
                .addComponent(btnCalendarConFormato)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalendarSinFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarSinFormatoActionPerformed
        // TODO add your handling code here:
        Calendar today = Calendar.getInstance();
        JOptionPane.showMessageDialog(null, "Hoy es "+today);
    }//GEN-LAST:event_btnCalendarSinFormatoActionPerformed

    private void btnCalendarConFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarConFormatoActionPerformed
        // TODO add your handling code here:
        Calendar today = Calendar.getInstance();
        JOptionPane.showMessageDialog(null, "Hoy es "+today.getTime());
    }//GEN-LAST:event_btnCalendarConFormatoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalendarConFormato;
    private javax.swing.JButton btnCalendarSinFormato;
    private javax.swing.JLabel lblEjemplos;
    // End of variables declaration//GEN-END:variables
}
