/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ister.vista.formularios.internos;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Paola
 */
public class FrmiEjemplosDateUtil extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmiEjemplos
     */
    public FrmiEjemplosDateUtil() {
        initComponents();
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEjemplos = new javax.swing.JLabel();
        btnDateSinFormato = new javax.swing.JButton();
        btnDateConFormato = new javax.swing.JButton();

        lblEjemplos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEjemplos.setText("Ejemplos");

        btnDateSinFormato.setText("Date sin formato");
        btnDateSinFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateSinFormatoActionPerformed(evt);
            }
        });

        btnDateConFormato.setText("Date con formato");
        btnDateConFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateConFormatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(lblEjemplos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDateConFormato)
                            .addComponent(btnDateSinFormato))))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEjemplos)
                .addGap(67, 67, 67)
                .addComponent(btnDateSinFormato)
                .addGap(35, 35, 35)
                .addComponent(btnDateConFormato)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDateSinFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateSinFormatoActionPerformed
        // TODO add your handling code here:
        Date fecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        JOptionPane.showMessageDialog(null,formato.format(fecha));
    }//GEN-LAST:event_btnDateSinFormatoActionPerformed

    private void btnDateConFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateConFormatoActionPerformed
        // TODO add your handling code here:
        java.sql.Date fecha = new java.sql.Date(1900);
        //SimpleDateFormat formato = new SimpleDateFormat("");
        JOptionPane.showMessageDialog(null,fecha.getDate());
    }//GEN-LAST:event_btnDateConFormatoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDateConFormato;
    private javax.swing.JButton btnDateSinFormato;
    private javax.swing.JLabel lblEjemplos;
    // End of variables declaration//GEN-END:variables
}
