/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ister.vista.formularios.internos;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Paola
 */
public class FrmiCalendar extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCalendar
     */
    public FrmiCalendar() {
        initComponents();
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtGrupo2 = new javax.swing.ButtonGroup();
        lblCalendar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbtTeoria = new javax.swing.JRadioButton();
        rbtEjemplos = new javax.swing.JRadioButton();
        rbtPractica = new javax.swing.JRadioButton();
        escritorioCalendar = new javax.swing.JDesktopPane();

        lblCalendar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCalendar.setText("Calendar");

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setForeground(new java.awt.Color(255, 204, 255));

        rbtGrupo2.add(rbtTeoria);
        rbtTeoria.setText("Teoría");
        rbtTeoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtTeoriaActionPerformed(evt);
            }
        });

        rbtGrupo2.add(rbtEjemplos);
        rbtEjemplos.setText("Ejemplos");
        rbtEjemplos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEjemplosActionPerformed(evt);
            }
        });

        rbtGrupo2.add(rbtPractica);
        rbtPractica.setText("Práctica");
        rbtPractica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPracticaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtTeoria)
                    .addComponent(rbtEjemplos)
                    .addComponent(rbtPractica))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(rbtTeoria)
                .addGap(18, 18, 18)
                .addComponent(rbtEjemplos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(rbtPractica)
                .addGap(31, 31, 31))
        );

        escritorioCalendar.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout escritorioCalendarLayout = new javax.swing.GroupLayout(escritorioCalendar);
        escritorioCalendar.setLayout(escritorioCalendarLayout);
        escritorioCalendarLayout.setHorizontalGroup(
            escritorioCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorioCalendarLayout.setVerticalGroup(
            escritorioCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(escritorioCalendar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(lblCalendar)
                .addContainerGap(359, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCalendar)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 213, Short.MAX_VALUE))
                    .addComponent(escritorioCalendar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtTeoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtTeoriaActionPerformed
        // TODO add your handling code here:
        escritorioCalendar.removeAll();
        escritorioCalendar.repaint();
        
        FrmiTeoriaCalendar frmiTeoriaCalendar = new FrmiTeoriaCalendar();
        escritorioCalendar.add(frmiTeoriaCalendar);
        frmiTeoriaCalendar.setVisible(true);
        
        try {
            frmiTeoriaCalendar.setMaximum(true);
            frmiTeoriaCalendar.setMaximizable(true);
            frmiTeoriaCalendar.setSelected(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_rbtTeoriaActionPerformed

    private void rbtEjemplosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEjemplosActionPerformed
        // TODO add your handling code here:
        escritorioCalendar.removeAll();
        escritorioCalendar.repaint();
        
        FrmiEjemplosCalendar frmiEjemplosCalendar = new FrmiEjemplosCalendar();
        escritorioCalendar.add(frmiEjemplosCalendar);
        frmiEjemplosCalendar.setVisible(true);
        
        try {
            frmiEjemplosCalendar.setMaximum(true);
            frmiEjemplosCalendar.setMaximizable(true);
            frmiEjemplosCalendar.setSelected(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_rbtEjemplosActionPerformed

    private void rbtPracticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPracticaActionPerformed
        // TODO add your handling code here:
        escritorioCalendar.removeAll();
        escritorioCalendar.repaint();
        
        FrmiPracticaCalendar frmiPracticaCalendar = new FrmiPracticaCalendar();
        escritorioCalendar.add(frmiPracticaCalendar);
        frmiPracticaCalendar.setVisible(true);
        
        try {
            frmiPracticaCalendar.setMaximum(true);
            frmiPracticaCalendar.setMaximizable(true);
            frmiPracticaCalendar.setSelected(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_rbtPracticaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorioCalendar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCalendar;
    private javax.swing.JRadioButton rbtEjemplos;
    private javax.swing.ButtonGroup rbtGrupo2;
    private javax.swing.JRadioButton rbtPractica;
    private javax.swing.JRadioButton rbtTeoria;
    // End of variables declaration//GEN-END:variables
}
