/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ister.vista.formularios.internos;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Paola
 */
public class FrmiTime extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmiTime
     */
    public FrmiTime() {
        initComponents();
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtGrupo3 = new javax.swing.ButtonGroup();
        lblTime = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbtTeoria = new javax.swing.JRadioButton();
        rbtEjemplos = new javax.swing.JRadioButton();
        rbtPractica = new javax.swing.JRadioButton();
        escritorioTime = new javax.swing.JDesktopPane();

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTime.setText("Time");

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        rbtGrupo3.add(rbtTeoria);
        rbtTeoria.setText("Teoría");
        rbtTeoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtTeoriaActionPerformed(evt);
            }
        });

        rbtGrupo3.add(rbtEjemplos);
        rbtEjemplos.setText("Ejemplos");
        rbtEjemplos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEjemplosActionPerformed(evt);
            }
        });

        rbtGrupo3.add(rbtPractica);
        rbtPractica.setText("Práctica");
        rbtPractica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPracticaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtTeoria)
                    .addComponent(rbtPractica)
                    .addComponent(rbtEjemplos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(rbtTeoria)
                .addGap(28, 28, 28)
                .addComponent(rbtEjemplos)
                .addGap(30, 30, 30)
                .addComponent(rbtPractica)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        escritorioTime.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout escritorioTimeLayout = new javax.swing.GroupLayout(escritorioTime);
        escritorioTime.setLayout(escritorioTimeLayout);
        escritorioTimeLayout.setHorizontalGroup(
            escritorioTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorioTimeLayout.setVerticalGroup(
            escritorioTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(escritorioTime)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(368, Short.MAX_VALUE)
                .addComponent(lblTime)
                .addGap(340, 340, 340))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTime)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 151, Short.MAX_VALUE))
                    .addComponent(escritorioTime))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtTeoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtTeoriaActionPerformed
        // TODO add your handling code here:
        escritorioTime.removeAll();
        escritorioTime.repaint();
        
        FrmiTeoriaTime frmiTeoriaTime = new FrmiTeoriaTime();
        escritorioTime.add(frmiTeoriaTime);
        frmiTeoriaTime.setVisible(true);
        
        try {
            frmiTeoriaTime.setMaximum(true);
            frmiTeoriaTime.setMaximizable(true);
            frmiTeoriaTime.setSelected(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_rbtTeoriaActionPerformed

    private void rbtEjemplosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEjemplosActionPerformed
        // TODO add your handling code here:
        escritorioTime.removeAll();
        escritorioTime.repaint();
        
        FrmiEjemplosTime frmiEjemplosTime = new FrmiEjemplosTime();
        escritorioTime.add(frmiEjemplosTime);
        frmiEjemplosTime.setVisible(true);
        
        try {
            frmiEjemplosTime.setMaximum(true);
            frmiEjemplosTime.setMaximizable(true);
            frmiEjemplosTime.setSelected(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_rbtEjemplosActionPerformed

    private void rbtPracticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPracticaActionPerformed
        // TODO add your handling code here:
        escritorioTime.removeAll();
        escritorioTime.repaint();
        
        FrmiPracticaTime frmiPracticaTime = new FrmiPracticaTime();
        escritorioTime.add(frmiPracticaTime);
        frmiPracticaTime.setVisible(true);
        
        try {
            frmiPracticaTime.setMaximum(true);
            frmiPracticaTime.setMaximizable(true);
            frmiPracticaTime.setSelected(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_rbtPracticaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorioTime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JRadioButton rbtEjemplos;
    private javax.swing.ButtonGroup rbtGrupo3;
    private javax.swing.JRadioButton rbtPractica;
    private javax.swing.JRadioButton rbtTeoria;
    // End of variables declaration//GEN-END:variables
}
